apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev-quota
spec:
  limits:
  - type: Container
    max:
      cpu: "500m"
      memory: "512Mi"
    default:
      cpu: "200m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
      
    