apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: dev-quota
spec:
  hard:
    pods: "3"
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: "1Gi"
