apiVersion: v1
kind: Service
metadata:
    name: color-app-service
    namespace: dev01
spec:
    type: NodePort
    selector:
        app: color-app-v1
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30012
